### ISSUE TITLE
add image

### ISSUE THREAD

**Issue by ghost** [PagarUbuntu-Indonesia/PagarUbuntu-Indonesia.github.io#7]
![ok](https://user-images.githubusercontent.com/10298895/32209127-99446b64-be41-11e7-9edd-e6332d343870.png)

**Comment by ghost** [comment]
@matematikaadit tolong ditambah

**Comment by matematikaadit** [comment]
Bisa submit PR? Gambarnya taruh di `README.md` mungkin?

**Comment by taufiqur-rahman** [comment]
:3

**Comment by ghost** [comment]
Super sekali reaksi bapak @taufiqur-rahman
